apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: core-inventory-system-frontend-image
    newName: ghcr.io/eed-web-application/core-inventory-system-frontend:sha-d4ff18d